# Generated by Django 5.1.6 on 2025-03-13 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_otp_verfied',
            new_name='is_otp_verified',
        ),
    ]
