# Generated by Django 5.1.6 on 2025-03-24 04:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolepermission',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app.menu'),
        ),
        migrations.AlterField(
            model_name='rolepermission',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='permissions', to='app.role'),
        ),
    ]
