# Generated by Django 5.1.6 on 2025-03-12 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_user_email_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email_verified',
        ),
    ]
